# Generated by Django 4.0.4 on 2023-03-16 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='friend',
            options={'ordering': ('-friend_update', '-timestamp')},
        ),
    ]
