# Generated by Django 4.0.4 on 2023-03-08 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_group'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Group',
            new_name='CustomGroup',
        ),
    ]
