# Generated by Django 4.0.4 on 2023-03-10 19:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_customgroup_is_admin_remove_customgroup_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppaticipant',
            name='user',
        ),
        migrations.AddField(
            model_name='grouppaticipant',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
