# Generated by Django 4.0.4 on 2023-03-11 14:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_grouppaticipant_user_grouppaticipant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grouppaticipant',
            name='user',
        ),
        migrations.AddField(
            model_name='grouppaticipant',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
